language: python
python:
          - "2.7"
install:
          - pip install flake8
          - pip install python-coveralls
script:
          - flake8 retweet || (echo "Please run a linter and fix errors "; false)
after_success:
          - coveralls
